---
name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PRESET: "none"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake --preset ${{env.PRESET}}

      - name: Build
        run: cmake --build --preset ${{env.PRESET}}

      - name: Test
        run: ctest --preset ${{env.PRESET}}
